# @format

- name: disable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y # its homogenious useful for red hat family

- name: enable nodejs 20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: "{{item}}"
    state: latest
  loop:
    - nodejs
    - mysql

- name: run app pre requasites
  ansible.builtin.import_role:
    name: comman
    tasks_from: app-pre-req.yml

# - name: create expense user
#   ansible.builtin.user: # hetrogenious used for all distros
#     name: expense
# - name: create a app directory
#   ansible.builtin.file:
#     path: /app
#     state: directory

# - name: download backend code
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
#     dest: /tmp/backend.zip

# - name: unzip backend code
#   ansible.builtin.unarchive:
#     src: /tmp/backend.zip #y default checks in ansible server
#     dest: /app
#     remote_src: yes

- name: install npm Dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: Copy backend service
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: Install MY SQL Dependencies
  ansible.builtin.pip:
    name:
      - PyMySQL #to connect my sql d from ansible server
      - cryptography
    executable: pip3.9
- name: import data into mysql
  community.mysql.mysql_db:
    name: all
    login_user: "{{login_user}}"
    login_password: "{{mysql_root_password}}"
    login_host: "{{login_host}}"
    state: import
    target: /app/schema/backend.sql

- name: demon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable backend
  ansible.builtin.service:
    name: backend
    state: started
    enabled: yes
