- name: install nginx
  ansible.builtin.dnf:
    name: nginx 
    state: latest 

- name: start and enable nginx 
  ansible.builtin.service:
    name: nginx 
    state: started 
    enabled: yes 

- name: run app pre requasites
  ansible.builtin.import_role:
    name: comman
    tasks_from: app-pre-req.yml

# - name: delete default website
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: absent

# - name: Create a default website
#   ansible.builtin.file:
#     path: /usr/share/nginx/html
#     state: directory

# - name: download and extract frontend code 
#   ansible.builtin.unarchive:
#     src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
#     dest: /usr/share/nginx/html
#     remote_src: yes

- name: Copy the reverse proxy nginx server 
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify: restart nginx

# if there is a any changes in above configuration then only u need to restart

# - name: Restart nginx 
#   ansible.builtin.service:
#     name: nginx
#     state: restartedd