- name: install MY SQL server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest
- name: start and enable MY SQL server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
- name: Install MY SQL Dependencies
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

# check password is already setup or not
# verify that Ansible can successfully connect to the MySQL server and fetch its version
- name: check db connection
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: "{{login_host}}"
    filter: version
  ignore_errors: yes
  register: mysql_connection_output
- name: print db connection output
  ansible.builtin.debug:
    msg: "{{mysql_connection_output}}"
- name: setup root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}"
  when: mysql_connection_output.failed is true # dont give when condtions in {{}} and not True